### ISSUE TITLE
race condition in barrier.js

### ISSUE THREAD

**Issue by binji** [lars-t-hansen/parlib-simple#30]
I tried running test-barrier.html in Chrome, and kept getting deadlocks. I instrumented the code and found that barrier can race in the following scenario:

    const seq = Atomics.load(iab, seqLoc);
    if (Atomics.sub(iab, counterLoc, 1) == 1) {
      const numAgents = iab[numAgentsLoc];
      iab[counterLoc] = numAgents;
      iab[seqLoc] = seq + 1;
      // LABEL A
      Atomics.futexWake(iab, seqLoc, numAgents - 1);
    } else {
      // LABEL B
      Atomics.futexWait(iab, seqLoc, seq, Number.POSITIVE_INFINITY);
    }

1) thread 4 arrives at LABEL B, with seq 4
2) thread 3 arrives at LABEL A, waking seq 4. iab[seqLoc] is set to 5.
3) thread 4 runs. iab[seqLoc] is set to 5, but seq is 4, so it doesn't wait.
4) thread 4 continues to run and hits the next barrier (using the same barrier object). This time the seq matches (iab[seqLoc] == 5), so it waits on the futex.
5) thread 3 runs, still waking seq 4. But now thread 4 is also woken up (with seq 5).

**Comment by lars-t-hansen** [comment]
Thanks for bringing this up.  I think I discovered the same problem in connection with Issue #26 but neglected to fix it because the bug in that case turned out to be a futex implementation bug.  There's a proof-of-concept fix on the branch "issue26", but for the asymmetric-barrier, not for this barrier.
